"use client"; // Use client component because of usePathname()
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./component/NavBar";
import { Footer } from "./component/Footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Check if we are on the root layout page where we want text-center
  const isRootLayout = pathname === "/"; // Change this condition as needed

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar />
        <main className={`min-h-screen ${isRootLayout ? "text-center" : ""}`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
